name: MobLimitter
version: '${project.version}'
main: com.peepersoak.moblimitter.MobLimitter
api-version: 1.19
commands:
  removetimer:
    description: Remove the Death Timer
  open:
    description: Base command
  moveworld:
    description: Base command
  world:
    description: Base command
  val:
    description: Base command
  account:
    description: Base command
